#Load libraries
```{r}
#libraries
library(tidyverse)
library(here)
library(tidyverse)
library(ggmap)
library(ggpmisc)
library(stringr)
library(sf)
library(sp)
library(spatialEco)
library(rnaturalearth)
library(taxize)
#check here
here::here()
```

#Download raw data
```{r}
rawdf <- read.csv(here("data", "rawdata", "cblawas.Reef Fish Survey.ABUNDANCEBIOMASS.2024-01-09T15.52.46.csv"))
```

#Abundance and Biomass
```{r}
#Begin data import and cleaning on abundance and biomass data
names(rawdf) <- tolower(names(rawdf))
rawdf <- filter(rawdf, projectagency == "=SCDNR-MARMAP")
rawdf <- rawdf %>% dplyr::select(date, eventname, collectionnumber, speciescommonname, speciesscientificname, speciescode, numbertotal, speciestotalweight, speciessubweight, specieswgtprocessed, tempsurface, tempbottom, salinitysurface, salinitybottom, sdo, bdo, latitudestart, latitudeend, longitudestart, longitudeend)
rawdf <- data.frame(apply(rawdf, 2, function(x) {x <- gsub("=", "", x) }))
rawdf$date <- as.Date(rawdf$date, format = "%m-%d-%Y")
rawdf$year <- as.numeric(format(rawdf$date, "%Y"))
rawdf$month <- as.numeric(format(rawdf$date, "%m"))
rawdf <- rawdf[!is.na(rawdf$date),]
rawdf$speciestotalweight <- as.numeric(rawdf$speciestotalweight)
rawdf <- filter(rawdf, speciestotalweight > 0)
rawdf$latitudestart <- as.numeric(rawdf$latitudestart)
rawdf$longitudestart <- as.numeric(rawdf$longitudestart)
backup <- rawdf

#names
for(i in 1:nrow(rawdf)) {
  if(rawdf$speciesscientificname[[i]] == "HAEMULON PLUMIERII") {
    rawdf$speciescommonname[[i]] <- "WHITE GRUNT"
  }
  if(rawdf$speciesscientificname[[i]] == "HAEMULON PLUMIERII") {
    rawdf$speciescommonname[[i]] <- "WHITE GRUNT"
  }
  if(rawdf$speciesscientificname[[i]] == "OPSANUS"){
    rawdf$speciescommonname[[i]] <- "LEOPARD TOArawdfISH"
  }
  if(rawdf$speciesscientificname[[i]] == "BODIANUS"){
    rawdf$speciescommonname[[i]] <- "SPOTFIN HOGFISH"
  }
  if(rawdf$speciesscientificname[[i]] == "CONGER"){
    rawdf$speciescommonname[[i]] <- "CONGER EEL"
  }
  if(rawdf$speciesscientificname[[i]] == "EMBLEMARIA"){
    rawdf$speciescommonname[[i]] <- "SAILFIN BLENNY"
  }
  if(rawdf$speciesscientificname[[i]] == "EMBLEMARIA"){
    rawdf$speciescommonname[[i]] <- "SAILFIN BLENNY"
  }
  if(rawdf$speciesscientificname[[i]] == "PAREQUES UMBROSUS"){
    rawdf$speciescommonname[[i]] <- "CUBBYU"
  }
  if(rawdf$speciesscientificname[[i]] == "MURAENA"){
    rawdf$speciescommonname[[i]] <- "RETICULATE MORAY"
  }
  if(rawdf$speciesscientificname[[i]] == "MURAENA"){
    rawdf$speciescommonname[[i]] <- "RETICULATE MORAY"
  }
  if(rawdf$speciescommonname[[i]] == "SCUP"){
    rawdf$speciescommonname[[i]] <- "STENTOMUSPORGIES"
  }
}

rawdf <- rawdf[!(is.na(rawdf$speciescommonname) | rawdf$speciescommonname==""), ]
rawdf$speciescommonname <- gsub(" ", "", rawdf$speciescommonname , fixed = TRUE)

#get families
uniquescinames <- unique(rawdf$speciesscientificname)
uniquescinames <- as.data.frame(uniquescinames)
uniquescinames$speciesscientificname <- uniquescinames$uniquescinames
uniquescinames <- dplyr::select(uniquescinames, speciesscientificname)
uniquescinames <- unique(uniquescinames)

#takes 3.5 min
#I set an API key for ENTREZ but hopefully no one else needs to 
#this throws 400 errors like crazy -- start loop over from wherever it stops to fix
#for CALAMUS options, just hit enter
for(i in 1:nrow(uniquescinames)) {
  familyinfo <- tax_name(uniquescinames$speciesscientificname[[i]], get = 'family', db = 'ncbi')
  uniquescinames$family[i] <- familyinfo$family
  print(paste("done", i))
}
uniquescinames$family <- as.character(uniquescinames$family)

backup <- uniquescinames

#taxize couldn't find these
uniquescinames$family <- ifelse(uniquescinames$speciesscientificname == "HOLOCENTRUS ASCENSIONIS", "Holocentridae", uniquescinames$family)
uniquescinames$family <- ifelse(uniquescinames$speciesscientificname == "RYPTICUS MACULATUS", "Serranidae", uniquescinames$family)

#said one is a grasshopper 
uniquescinames$family <- ifelse(uniquescinames$speciesscientificname == "CALAMUS", "Sparidae", uniquescinames$family)
# write.csv(uniquescinames, here("data", "processeddata", "RFS_Families.csv"))

rawdf <- merge(rawdf, uniquescinames, by = "speciesscientificname")

#what family na's
nafamily <- dplyr::filter(rawdf, is.na(family))
#angelfish hybrid??
```

```{r}
#eda stuff
cleandf <- filter(rawdf, month %in% 5:9)
cleandf$tempsurface <- as.numeric(cleandf$tempsurface)
cleandf <- filter(cleandf, tempsurface != 0)

#export processed
# write.csv(df, here("data", "processeddata", "RFS_AbundanceBiomass.csv"))
```

#Event
```{r}
#Event data (only need depth)
event <- read.csv(here("data", "rawdata", "cblawas.Reef Fish Survey.EVENT.2024-01-11T11.18.10.csv"))
names(event) <- tolower(names(event))
event <- filter(event, projectagency == "=SCDNR-MARMAP")
event <- event %>% dplyr::select(date, eventname, collectionnumber, depthstart, depthend, duration)
event <- data.frame(apply(event, 2, function(x) {x <- gsub("=", "", x) }))
event$date <- as.Date(event$date, format = "%m-%d-%Y")
event$year <- as.numeric(format(event$date, "%Y"))
event$month <- as.numeric(format(event$date, "%m"))
event <- event[!is.na(event$date),]
eventnames <- unique(event$eventname)
collectionnumbers <- unique(event$collectionnumber)
event <- event %>% dplyr::select(eventname, depthstart, depthend, duration)
#ig use event names

#export event data to processed
# write.csv(df, here("data", "processeddata", "RFS_EventDepth.csv"))
```

```{r}
#merge event and abundance biomass to get depth
cleandfwevent <- merge(cleandf, event, by = "eventname")

#export data with depths to processed
# write.csv(cleandfwevent, here("data", "processeddata", "RFS_AbundanceBiomassDepth.csv"))
```

```{r}
#check out length data
length <- read.csv(here("data", "rawdata", "cblawas.Reef Fish Survey.LENGTHFREQUENCY.2024-01-11T11.19.34.csv"))
names(length) <- tolower(names(length))
length <- filter(length, projectagency == "=SCDNR-MARMAP")
length <- length %>% dplyr::select(date, eventname, collectionnumber, speciescommonname, speciesscientificname, speciescode, lengthunits, lengthtypecode, length, numbermeasure, totalnumber, tempsurface, tempbottom, salinitysurface, salinitybottom, sdo, bdo, latitudestart, latitudeend, longitudestart, longitudeend)
length <- data.frame(apply(length, 2, function(x) {x <- gsub("=", "", x) }))
length$date <- as.Date(length$date, format = "%m-%d-%Y")
length$year <- as.numeric(format(length$date, "%Y"))
length$month <- as.numeric(format(length$date, "%m"))
length <- length[!is.na(length$date),]

# write.csv(length, here("data", "processeddata", "RFS_Length.csv"))
```

#Specimen

```{r}
#check out specimen data
specimen <- read.csv(here("data", "rawdata", "cblawas.Reef Fish Survey.SPECIMEN.2024-01-11T11.47.58.csv"))
names(specimen) <- tolower(names(specimen))
specimen <- filter(specimen, projectagency == "=SCDNR-MARMAP")
specimen <- specimen %>% dplyr::select(date, eventname, collectionnumber, speciescommonname, speciesscientificname, speciescode, duration, speciestotalweight, len1, len1_type, len2, len2_type, len3, len3_type, len4, len4_type, orglenunits, weight, orgwtunits, estimatedweight, sexdescription, maturitydescription, diseasedesc, baittype, tempsurface, tempbottom, salinitysurface, salinitybottom, sdo, bdo, latitudestart, latitudeend, longitudestart, longitudeend )
specimen <- data.frame(apply(specimen, 2, function(x) {x <- gsub("=", "", x) }))
specimen$date <- as.Date(specimen$date, format = "%m-%d-%Y")
specimen$year <- as.numeric(format(specimen$date, "%Y"))
specimen$month <- as.numeric(format(specimen$date, "%m"))
specimen <- specimen[!is.na(specimen$date),]

# write.csv(specimen, here("data", "processeddata", "RFS_Specimen.csv"))
```

#Post cleaning
We are interested in how the reef fish community has changed over time. We could do a multidimensional analysis of community composition, a tree based model of what environmental factors drive distributions of fishes, 


```{r}
#mapping info
myLocation <- c(min(df$longitudestart)-2, min(df$latitudestart)-2,max(df$longitudestart)+2,max(df$latitudestart)+2)
myMap <- get_map(location=myLocation, source="stamen", color="bw")
```

#Sampling effort

```{r}
#sampling effort EDA
ggplot(data = cleandf, mapping = aes(x = year, y = month)) + geom_point()

#seems like early and late months maybe shouldn't be sampled
df %>% group_by(month) %>% ggplot(mapping = aes(x = year, y = speciestotalweight)) + geom_point() + geom_line() + facet_wrap(~month)
# put this at top
# df <- filter(df, month %in% 5:9)
#temperature
ggplot(data = df, mapping = aes(x = date, y = tempsurface)) + geom_point() + geom_smooth(method = "lm")

#remove temps at 0 (impossible), we can do things without temps but I think we need them
# put this at top
# df <- filter(df, tempsurface != 0)

#temperature again
ggplot(data = df, mapping = aes(x = date, y = tempsurface)) + geom_point() + geom_smooth(method = "lm") + stat_poly_eq(formula = y ~ x, aes(label = paste(..eq.label.., ..p.value.label.., sep = "*`,`~")), parse = TRUE, label.x.npc = "right", vstep = 0.05, size = 2.4)


floor_decade = function(value){ return(value - value %% 5) }
decade <- mutate(df, decade = floor_decade(year))

ggmap(myMap) + geom_point(data = decade , aes(y = latitudestart, x = longitudestart), size = 0.5) + xlab("Longitude") + ylab("Latitude") +  theme(legend.position = "none") + facet_wrap(~decade) + ggtitle("RFS Sampling Effort over Time")

# ggsave(here("figures", "EDA", "SamplingEffortby5yrs.png"), width = 6, height = 5, unit = "in")
```


```{r}
#Find range of oldest years to make a shapefile
oldest1990 <- dplyr::filter(df, year == 1990)
oldest2000 <- dplyr::filter(df, year == 2000)

ggmap(myMap) + geom_point(data = oldest2000, aes(y = latitudestart, x = longitudestart, color = year)) + xlab("Longitude") + ylab("Latitude") +  theme(legend.position = "none") 

#export these to arc (will use 1990 one)
# write.csv(oldest1990, here("data", "processeddata","reefsurveylocations1990.csv"))
# write.csv(oldest2000, here("data", "processeddata","reefsurveylocations2000.csv"))

```

#Grid
```{r}
tomtates <- df %>% filter(speciescommonname == "TOMTATE")
#station codes are too unique. going to subset by grid
tomtates <- tomtates %>% dplyr::select(date, month, year, tempsurface, tempbottom, salinitybottom, salinitysurface, sdo, bdo, duration, depthstart, latitudestart, longitudestart) %>% na.omit

#get spatial data
world <- ne_countries(scale = "medium", returnclass = "sf")
# make an object the size and shape of the output you want
globe_bb <- matrix(c(-83.22,25.23,
                      -83.22,37.02,
                      -73.45,37.02,
                     -73.45, 25.23,
                     -83.22,25.23), byrow = TRUE, ncol = 2) %>%
  list() %>% 
  st_polygon() %>% 
  st_sfc(., crs = 4326)


#checkit
ggplot(data = world) + geom_sf() +geom_sf(data = globe_bb) +
    coord_sf(xlim=c(-84, -72), ylim=c(25,38), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black"))

# generate grid of 128 x 128 tiles (each .5 x .5 degrees)
globe_grid_18x18 <- st_make_grid(globe_bb, n = c(20, 20), 
                                 crs = 4326, what = 'polygons') %>%
  st_sf('geometry' = ., data.frame('ID' = 1:length(.)))

#idk what this does
coordinates(tomtates) <- ~ longitudestart + latitudestart
df <- st_as_sf(tomtates)

df <- st_set_crs(df, 4326)
grid <- globe_grid_18x18

#spatial intersections 2 mon tomtates
df_extract <- st_intersection(df, grid)
df_extract_2 <- as.data.frame(df_extract)

#pretty picture
df_extract_point <- df_extract_2$geometry
plot(st_geometry(df_extract_point))


df_extract_2$gridID <- df_extract_2$ID
df_extract_2$coords <- do.call(rbind, st_geometry(df_extract_point)) %>% 
    as_tibble() %>% setNames(c("longitude","latitude"))
df_extract_2 <- unnest(df_extract_2)

#change to grid id
df_extract_2$gridID <- df_extract_2$ID
df_extract_2$coords <- do.call(rbind, st_geometry(df_extract_point)) %>%
    as_tibble() %>% setNames(c("lon","lat"))

#duplicates ?
df_extract_2_2 <- df_extract_2[!duplicated(df_extract_2[c("date", "longitude","latitude")]),] 

#plot in squares
ggplot(data = world) + geom_sf() + geom_sf(data = globe_grid_18x18)  + geom_point(data = df_extract_2_2, aes(x = longitude, y = latitude, color = gridID)) +
    coord_sf(xlim=c(-84, -72), ylim=c(25,38), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + ggtitle("Subsetted Points") + ggtitle("Grid Subset") + xlab("Longitude") + ylab("Latitude") 

tomtates <- df_extract_2_2
```

```{r}
#subset data only in 1990 survey geographic range
require(sf)
shape <- sf::read_sf(file.path(here("data", "rawdata", "shapefiles", "surveypolygons_ExportFeature1.shp")))
shape <- st_transform(shape, crs = 4326)

#get world map data
world <- ne_countries(scale = "medium", returnclass = "sf")

#checkit
ggplot(data = world) + geom_sf() +geom_sf(data = shape, fill = "blue") +
  coord_sf(xlim=c(-83, -70), ylim=c(25,38), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black"))

#idk what this does
 coordinates(df) <- ~ longitudestart + latitudestart
# coordinates(df) <- ~ longitude + latitude
df <- st_as_sf(df)

df <- st_set_crs(df, 4326)
grid <- shape

#spatial intersections? 
df_extract <- st_intersection(df, grid)
df_extract_2 <- as.data.frame(df_extract)

#pretty picture
df_extract_point <- df_extract_2$geometry
plot(st_geometry(df_extract_point))


df_extract_2$gridID <- df_extract_2$Class
df_extract_2$coords <- do.call(rbind, st_geometry(df_extract_point)) %>% 
  as_tibble() %>% setNames(c("longitude","latitude"))
df_extract_2 <- unnest(df_extract_2)
df_extract_2_2 <- df_extract_2[!duplicated(df_extract_2[c("date", "longitude","latitude")]),] 
ggplot(data = world) + geom_sf() + geom_sf(data = shape)  + geom_point(data = df_extract_2_2, aes(x = longitude, y = latitude)) +
  coord_sf(xlim=c(-83, -70), ylim=c(25,38), expand = TRUE) + theme(panel.background = element_rect(fill = "white", colour = "black")) + ggtitle(paste( "Subsetted Points")) + ggtitle(paste("Grid Subset")) + xlab("Longitude") + ylab("Latitude")

df_extract_2_2 <- mutate(df_extract_2_2, decade = floor_decade(year))

ggmap(myMap) + geom_point(data = df_extract_2_2 , aes(y = latitude, x = longitude), size = 0.5) + xlab("Longitude") + ylab("Latitude") +  theme(legend.position = "none") + facet_wrap(~decade) + ggtitle("RFS Sampling Effort over Time post Subset")
# ggsave(here("figures", "EDA", "SamplingEffortby5yrsPostSubset.png"), width = 6, height = 5, unit = "in")

df_extract_2_2 <- dplyr::select(df_extract_2_2, date, year, month, eventname, collectionnumber, speciescommonname, speciesscientificname, family, speciescode, numbertotal, speciestotalweight, speciessubweight, specieswgtprocessed, tempsurface, tempbottom, salinitysurface, salinitybottom, sdo, bdo, latitude, latitudeend, longitude, longitudeend, depthstart, depthend, duration)

#export processed
# write.csv(df_extract_2_2, here("data", "processeddata", "RFS_AbundanceBiomassDepthRangeLimit.csv"))
```